export { default as SignIn } from "./SignIn";
export { default as SignUp } from "./SignUp";
export { default as Home } from "./Home";
export { default as Menu } from "./Menu";
export { default as Discover } from "./Discover";
export { default as Place } from "./Place";
export { default as Rewards } from "./Rewards";
export { default as Scanner } from "./Scanner";
export { default as SignOut } from "./SignOut";
